Style/CaseEquality:
  Enabled: false
  
Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/Lambda:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Max: 150

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/MutableConstant:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true
  Exclude:
    - bin/**/*
    - config.ru
    - Gemfile
    - Rakefile

AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: '3.3'
  Exclude:
    - 'spec/factories/*.rb'
    - '*.gemspec'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'

Lint/DeprecatedConstants:
  Enabled: true

Style/AccessorGrouping:
  Enabled: false

Style/BlockForwarding:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false